In [28]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

In [29]:
data_hour_merge_24 = pd.read_csv('./datos_entrenamiento.csv')

### Saquemos las componentes del viento:

In [30]:
def componente_x(magnitud, direccion):
    comp_x = magnitud*np.cos(direccion)
    comp_y = magnitud*np.sin(direccion)
    lista = [comp_x,comp_y]
    return lista

In [31]:
data_hour_merge_24['WSP_x'] = 0
data_hour_merge_24['WSP_y'] = 0

lst = data_hour_merge_24.apply(lambda x: componente_x(x['WSP'], x['WDR']), axis=1)

data_hour_merge_24[['WSP_x']] = [item[0] for item in lst]
data_hour_merge_24[['WSP_y']] = [item[1] for item in lst]

In [32]:
data_hour_merge_24.head()

,CO,NO,NO2,NOX,O3,PM10,PM2.5,RH,SO2,TMP,...,WSP,dia,fecha,hora,id_station,mes,PM10mean,PM25mean,WSP_x,WSP_y
0,0.6,2.0,24.0,26.0,14.0,NaN,NaN,62.0,2.0,14.8,...,1.9,2,2016-01-02 00:00:00,0,AJM,1,NaN,NaN,1.663345,0.918304
1,NaN,NaN,NaN,NaN,16.0,NaN,3.0,92.0,NaN,8.5,...,1.3,2,2016-01-02 00:00:00,0,AJU,1,NaN,NaN,1.268310,0.285291
2,1.1,15.0,40.0,55.0,2.0,53.0,17.0,NaN,19.0,NaN,...,NaN,2,2016-01-02 00:00:00,0,CAM,1,NaN,NaN,NaN,NaN
3,0.9,3.0,39.0,42.0,11.0,NaN,19.0,NaN,NaN,NaN,...,NaN,2,2016-01-02 00:00:00,0,CCA,1,NaN,NaN,NaN,NaN
4,0.6,NaN,NaN,NaN,27.0,21.0,NaN,65.0,1.0,14.0,...,1.0,2,2016-01-02 00:00:00,0,CHO,1,NaN,NaN,-0.223741,-0.974649

### Arreglemos las fechas:

In [33]:
data_hour_merge_24 = data_hour_merge_24[(data_hour_merge_24.fecha > "2015-01-01 23:00:00")]
data_hour_merge_24['dia'] = data_hour_merge_24['dia'].astype(str).astype(float)
data_hour_merge_24['mes'] = data_hour_merge_24['mes'].astype(str).astype(float)

Creemos un diccionario con __data_hour_merge_24__ dividido por estación:

In [34]:
estaciones = data_hour_merge_24.id_station.unique().tolist()

data_est = {}
for elem in estaciones:
    data_est[elem] = data_hour_merge_24[data_hour_merge_24.id_station == elem]

In [35]:
data_hour_merge_24.head(5)

,CO,NO,NO2,NOX,O3,PM10,PM2.5,RH,SO2,TMP,...,WSP,dia,fecha,hora,id_station,mes,PM10mean,PM25mean,WSP_x,WSP_y
0,0.6,2.0,24.0,26.0,14.0,NaN,NaN,62.0,2.0,14.8,...,1.9,2.0,2016-01-02 00:00:00,0,AJM,1.0,NaN,NaN,1.663345,0.918304
1,NaN,NaN,NaN,NaN,16.0,NaN,3.0,92.0,NaN,8.5,...,1.3,2.0,2016-01-02 00:00:00,0,AJU,1.0,NaN,NaN,1.268310,0.285291
2,1.1,15.0,40.0,55.0,2.0,53.0,17.0,NaN,19.0,NaN,...,NaN,2.0,2016-01-02 00:00:00,0,CAM,1.0,NaN,NaN,NaN,NaN
3,0.9,3.0,39.0,42.0,11.0,NaN,19.0,NaN,NaN,NaN,...,NaN,2.0,2016-01-02 00:00:00,0,CCA,1.0,NaN,NaN,NaN,NaN
4,0.6,NaN,NaN,NaN,27.0,21.0,NaN,65.0,1.0,14.0,...,1.0,2.0,2016-01-02 00:00:00,0,CHO,1.0,NaN,NaN,-0.223741,-0.974649

In [36]:
data_hour_merge_24.to_csv("./datos_modelos_formateados.csv",sep=',', encoding='utf-8',index=False)